# Generated by Django 6.1 on 2026-09-20 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idAdm', models.AutoField(primary_key=True, serialize=False)),
                ('nomeAdm', models.CharField(max_length=150)),
                ('emailAdm', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('idInst', models.AutoField(primary_key=True, serialize=False)),
                ('nomeInst', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('conteudoInformativo', models.TextField()),
                ('servicosOferecidos', models.CharField(max_length=500)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('site', models.URLField(blank=True)),
                ('logradouro', models.CharField(max_length=250)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('horarioAtendimento', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instituicoes', to='ongs.administrador')),
            ],
        ),
    ]
